### ISSUE TITLE
Questions about pomelo

### ISSUE THREAD

**Issue by xuhenry** [spatialfruitsalad/pomelo#5]
Dear Dr. Spatialfruitsalad.
    I want to use the pomelo code to generate the voronoi cells of a series sphere particles with tightly connected. So that I call use the  voronoi cells to represent the same geometry model as the assembly of the sphere particles.
   But I failed. Will you help me ? Thanks.
   The tests results and the file are attached as follows.
   https://cloud.tsinghua.edu.cn/d/fbe2c2b912614f94960e/
Thanks a lot!
Best regards, 
Henry

**Comment by xuhenry** [comment]
Furthermore, is there any detailed documents about the code?
Thanks a lot!

**Comment by spatialfruitsalad** [comment]
Dear Dr. Xuhenry,

Thank you for your interest in Pomelo.

The general information on how to run pomelo can be found in the [github readme](https://github.com/spatialfruitsalad/pomelo, scroll down) as well as in the [linked paper](https://epjwoc.epj.org/articles/epjconf/abs/2017/09/epjconf162065/epjconf162065.html).
Another source can also be found in [this paper](https://aip.scitation.org/doi/10.1063/1.4983051).

Due to security reasons I will not/cannot access the files you sent me. 

If an error occurs, there should be a message logged in the console output. That might be the first place to look for what was incorrect.
Another easy check is to verify the file surface_triangulation.xyz, e.g. by plotting the surface of one examplary particle (e.g. with matlag, gnuplot or python) to verify that the surface discretization works as expected and that the particles are in the correct position.

Best regards,
Simon

**Comment by xuhenry** [comment]
Dear Dr. Spatialfruitsalad.
    Many thanks for your help. However the problems is still not resolved. 
    I have send the file to the e-mail.  simon.weis@fau.de and philipp.schoenhoefer@fau.de
Thanks a lot!
Best regards,
Henry

**Comment by xuhenry** [comment]
@spatialfruitsalad 
Dear Dr. Spatialfruitsalad.
   Although, the "If you come from 'Analyzing X-ray tomographies of granular packings' or 'Howto calculate the lpf distribution'"added, but it is still not clear how to use.
   And there is no examples about this.
Thanks a lot!
Best regards,
Henry.

**Comment by spatialfruitsalad** [comment]
Dear Dr. @xuhenry ,
It looks like the format of your input file is not correct. An error message while parsing should have been printed when you ran pomelo.

You can check the expected input format in `/src/parsexyzr.hpp`. An example of a valid xyzr file can be found in `test/2016-05-20_xyzr/hs-16384_0.50.xyzr`.
The first line in the file has to be a comment line, telling pomelo about the system parameters (boundary condition, boxsx, boxsy, boxsz, shrink, stepstheta and stepsphi).
Every following line has to contain exactly 4 numbers: x,y,z position of the sphere's centroid and the sphere's radius. No special characters should be present.

Furthermore I see that you are trying to use negative coordinates. Until now pomelo supports only coordinates from (0,0,0) to (boxsx,boxsy,boxsz). This can be corrected by shifting the positions to the first octant.

Best regards,
Simon
